[package]
name = "mrp-discount-function"
version = "1.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
shopify_function = { version = "2.0", features = ["typegen"] }
serde = { version = "1.0", features = ["derive"] }
