api_version = "2025-04"

[[extensions]]
name = "t:name"
handle = "mrp-discount-function"
type = "function"
uid = "2b384e3f-bbb5-12e2-5362-a55f7ec52f9d10f40852"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart_lines_discounts_generate_run"

  [[extensions.targeting]]
  target = "cart.delivery-options.discounts.generate.run"
  input_query = "src/cart_delivery_options_discounts_generate_run.graphql"
  export = "cart_delivery_options_discounts_generate_run"

  [extensions.build]
  command = "shopify function typegen && cargo build --target=wasm32-unknown-unknown --release"
  path = "target/wasm32-unknown-unknown/release/mrp-discount-function.wasm"
  watch = [ "src/**/*.rs" ]
